SELECT
	-- id,
	age,
	bmr,
	(CAST(weight AS FLOAT)/10)/(CAST(height AS FLOAT)/1000)^2	AS bmi,
	body_age,
	bone_slim,
	-- bone_slim_low,
	-- bone_slim_top,
	ecf,
	height,
	icf,
	-- lbm_low_limit,
	lbm_quantity,
	-- lbm_top_limit,
	-- mbf_low_limit,
	mbf_quantity,
	-- mbf_top_limit,
	-- mineral_low_limit,
	mineral_quantity,
	-- mineral_top_limit,
	msf_quantity,
	mvf_quantity,
	-- protein_low_limit,
	protein_quantity,
	-- protein_top_limit,
	sex,
	-- tbw_low_limit,
	tbw_quantity,
	-- tbw_top_limit,
	total_score,
	weight,
	whr_level
	-- macro_goal,
	-- macro_bodytype,
	-- macro_activitylevel,
	-- macro_activitytype,
	-- macro_fatloss
FROM member_scans
;